#!/usr/bin/env bash
# Configures HAProxy to load balance traffic between two web servers

apt-get update
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server web01 34.230.59.167:80 check
        server web02 3.92.212.141:80 check
EOF

service haproxy restart
