#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me with a 301 status

sed -i '/server_name _;/a\
\
        location /redirect_me {\
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
        }' /etc/nginx/sites-available/default

service nginx restart
